export const COLORS = {
    primary: "#2563eb",
    secondary: "#1e40af",
    text: "#1f2937",
    light: "#f8fafc",
    border: "#d1d5db",
    success: "#16a34a"
};

export function drawPageBorder(doc) {
    doc
        .save()
        .lineWidth(1)
        .strokeColor(COLORS.border)
        .rect(
            20,
            20,
            doc.page.width - 40,
            doc.page.height - 40
        )
        .stroke()
        .restore();
}

export function drawHeader(doc) {

    drawPageBorder(doc);

    doc
        .rect(20,20,doc.page.width-40,70)
        .fill(COLORS.primary);

    doc
        .fillColor("white")
        .font("Helvetica-Bold")
        .fontSize(24)
        .text("ExamNotes AI",40,42);

    doc
        .fontSize(10)
        .text("AI Powered Smart Study Notes",42,68);

    doc.fillColor(COLORS.text);

    doc.moveDown(3);
}

export function drawFooter(doc){

    doc
        .fontSize(9)
        .fillColor("gray")
        .text(
            "Generated by ExamNotes AI",
            0,
            doc.page.height-35,
            {
                align:"center"
            }
        );

    doc.fillColor(COLORS.text);
}

export function sectionTitle(doc,title){

    doc.moveDown();

    doc
        .font("Helvetica-Bold")
        .fontSize(17)
        .fillColor(COLORS.primary)
        .text(title);

    doc.moveDown(0.2);

    doc
        .moveTo(50,doc.y)
        .lineTo(550,doc.y)
        .strokeColor(COLORS.primary)
        .stroke();

    doc.moveDown();

    doc.fillColor(COLORS.text);
}